### ISSUE TITLE
1.18 Crash

### ISSUE THREAD

**Issue by m-sarabi** [xpple/SeedMapper#33] opened 2021-12-14 16:31 UTC
**Describe the bug**
Crash when joining a server

**To Reproduce**
Join a server

**Expected behavior**
Not crash

**Additional context**
mods:
- Fabric API 0.44.0
- ClientCommands
- Malilib
- MiniHUD
- Tweakeroo
- ModMenu
- SeedCrackerX 2.11.1
- Sodium 0.4.0-alpha5+build.816

Crash Report:
[crash-2021-12-14_19.51.34-client.txt](https://github.com/xpple/SeedMapper/files/7713180/crash-2021-12-14_19.51.34-client.txt)

**Comment by xpple** [comment] 2021-12-15 09:45
I will have a look right now.

**Comment by xpple** [comment] 2021-12-15 10:02
I couldn't reproduce this on 1.18. I'll update the mod to 1.18.1, maybe that'll fix it.

**Comment by xpple** [comment] 2021-12-15 10:58
This should now be fixed in [the latest release](https://modrinth.com/mod/seedmapper/version/cU57xj4T/). You may reopen this if the issue persists.

**Closed by xpple** 2021-12-15 10:58 UTC
Labels: bug
